id: I24D17F5F
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-fd1e
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 02:13:46.701977+00:00
last_modified: 2023-08-15 02:13:46.701983+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1452
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1452
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བའི་ཤེས་རབ།
  languages:
  - bo
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9510993838821425
  ocr_word_median_confidence_index: 0.9978337
bases:
  I3CN1454:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1454
      total_pages: 36
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1454.txt
    statistics:
      ocr_word_median_confidence_index: 0.9978337
      ocr_word_mean_confidence_index: 0.9510993838821425
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
